export type Cat =
  | "All"
  | "CNC & LASER CUTTING"
  | "LED & ILLUMINATION"
  | "CORPORATE BRANDING"
  | "PRINTING & SIGNBOARDS";

export interface Product {
  id: string;
  title: string;
  cat: Exclude<Cat, "All">;
  img: string;
  desc: string;
  price?: string;
  specs?: Record<string, string>;
  trade?: Record<string, string>;
  about?: { intro: string; sections: { heading: string; text: string }[] };
  faqs?: { q: string; a: string }[];
}

export const CATS: Cat[] = ["All", "CNC & LASER CUTTING", "LED & ILLUMINATION", "CORPORATE BRANDING", "PRINTING & SIGNBOARDS"];

export const RAW_PRODUCTS: Product[] = [
  // CNC & LASER CUTTING
  { id: "acp-router-cutting",    title: "ACP Router Cutting",               cat: "CNC & LASER CUTTING",    img: "/products/product-acp-router.png",          desc: "Precision ACP (Aluminium Composite Panel) router cutting for architectural cladding, facades and signage backdrops with clean, glassy edges.",                                                                                price: "Price on Request", specs: { "Material": "Aluminium Composite Panel (ACP)", "Cutting Accuracy": "±0.05 mm", "Thickness Supported": "3mm – 6mm", "Finish": "Mirror / Matte / Brushed", "Delivery Time": "2–3 Working Days" }, trade: { "Minimum Order Quantity": "1 Sheet", "Delivery Time": "2–3 Working Days" } },
  { id: "mdf-cnc-cutting",       title: "MDF CNC Laser Cutting",            cat: "CNC & LASER CUTTING",    img: "/products/mdf-cnc.jpg",                      desc: "High-precision MDF CNC laser cutting for intricate interior décor panels, display boards, signage bases and 3D-letter backing with zero burn marks.",                                                                              price: "Price on Request", specs: { "Material": "MDF (Medium Density Fibreboard)", "Cutting Accuracy": "±0.1 mm", "Thickness Supported": "3mm – 25mm", "Surface": "Paintable / Lamination Ready" }, trade: { "Minimum Order Quantity": "1 Sheet", "Delivery Time": "3–5 Working Days" } },
  { id: "acrylic-laser-cutting", title: "Acrylic Laser Cutting & Engraving",cat: "CNC & LASER CUTTING",   img: "/products/product-acrylic-laser.jpg",        desc: "Custom laser cutting and engraving on cast & extruded acrylic sheets for signage, trophies, display stands and branded name-boards.",                                                                                                  price: "Price on Request", specs: { "Material": "Cast / Extruded Acrylic", "Cutting Accuracy": "±0.05 mm", "Thickness Supported": "2mm – 20mm", "Colors Available": "All Standard & Custom" }, trade: { "Minimum Order Quantity": "1 Piece", "Delivery Time": "2–4 Working Days" } },
  { id: "cnc-aluminium-cutting", title: "CNC Aluminium Routing",            cat: "CNC & LASER CUTTING",    img: "/products/product-cnc-aluminium.png",        desc: "Heavy-duty CNC aluminium routing for channel letter blanks, architectural elements, cabinet fronts and premium outdoor signage frames.",                                                                                          price: "Price on Request", specs: { "Material": "Aluminium Sheets / Extrusions", "Cutting Accuracy": "±0.1 mm", "Thickness Supported": "1mm – 10mm", "Finish": "Anodized / Powder Coat / Raw" }, trade: { "Minimum Order Quantity": "1 Sheet", "Delivery Time": "3–5 Working Days" } },
  { id: "vacuum-foaming",        title: "Vacuum Foaming Signage",           cat: "CNC & LASER CUTTING",    img: "/products/product-vacuum-foaming.png",       desc: "Vacuum-formed 3D letter and logo moulds for illuminated signage fascias, retail display units and large-format brand installations.",                                                                                              price: "Price on Request", specs: { "Process": "Vacuum Thermoforming", "Material": "ABS / PETG / HIPS", "Max Size": "Custom", "Depth": "Up to 150mm" }, trade: { "Minimum Order Quantity": "5 Units", "Delivery Time": "5–7 Working Days" } },
  // LED & ILLUMINATION
  { id: "led-acrylic-signage",   title: "LED Acrylic Glow Signage",         cat: "LED & ILLUMINATION",     img: "/products/product-led-acrylic-signage.png",  desc: "Edge-lit and back-lit acrylic LED sign boards with vivid, uniform illumination — ideal for reception walls, storefronts and brand counters.",                                                                                        price: "Price on Request", specs: { "Light Source": "LED Strip / Module", "Acrylic Thickness": "6mm – 25mm", "Color Temperature": "Warm White / Cool White / RGB", "IP Rating": "IP54", "Power Consumption": "Low (Energy Efficient)" }, trade: { "Minimum Order Quantity": "1 Unit", "Delivery Time": "3–5 Working Days" } },
  { id: "led-outdoor-glow",      title: "LED Outdoor Glow Signs",           cat: "LED & ILLUMINATION",     img: "/products/product-led-outdoor-glow.png",     desc: "Weather-proof outdoor LED illuminated signs for building facades, hoarding panels and highway gantries — built to IP65 standards.",                                                                                              price: "Price on Request", specs: { "IP Rating": "IP65 (Weather-Proof)", "Brightness": "High Luminosity LEDs", "Casing": "Powder-Coated MS / SS", "Power Supply": "Enclosed SMPS", "Visibility": "Day & Night" }, trade: { "Minimum Order Quantity": "1 Unit", "Delivery Time": "5–7 Working Days" } },
  { id: "led-pylon-sign",        title: "LED Pylon Sign",                   cat: "LED & ILLUMINATION",     img: "/products/product-led-pylon.png",            desc: "Tall illuminated pylon signs for petrol stations, malls, hospitals and commercial complexes — fully fabricated in steel with LED face illumination.",                                                                              price: "Price on Request", specs: { "Structure": "MS / SS Fabricated", "Face Material": "Acrylic / ACP", "Height": "Custom (6ft – 30ft)", "Illumination": "Internal LED Modules", "Finish": "Powder Coat / Vinyl Wrap" }, trade: { "Minimum Order Quantity": "1 Unit", "Delivery Time": "7–14 Working Days" } },
  { id: "led-acrylic-neon",      title: "LED Acrylic Neon Sign",            cat: "LED & ILLUMINATION",     img: "/products/product-acrylic.jpg",              desc: "Flexible LED neon on acrylic backing — custom shapes, logos and lettering with the retro neon look and modern LED efficiency.",                                                                                                  price: "Price on Request", specs: { "Light Source": "Flexible LED Neon Tube", "Backing": "Clear / Frosted Acrylic", "Colors": "Single / Multi-color / RGB", "Power": "12V / 24V DC" }, trade: { "Minimum Order Quantity": "1 Piece", "Delivery Time": "3–5 Working Days" } },
  { id: "neon-sign",             title: "Glass Neon Signage",               cat: "LED & ILLUMINATION",     img: "/products/product-neon.jpg",                 desc: "Hand-blown traditional glass neon signs for restaurants, bars, studios and premium retail — every curve crafted by master neon artists.",                                                                                          price: "Price on Request", specs: { "Type": "Hand-bent Glass Neon", "Gas": "Neon / Argon", "Colors": "15+ Standard Colors", "Transformer": "High-Frequency Electronic" }, trade: { "Minimum Order Quantity": "1 Unit", "Delivery Time": "5–10 Working Days" } },
  { id: "digital-display",       title: "LED Digital Display",              cat: "LED & ILLUMINATION",     img: "/products/product-digital.jpg",              desc: "Pixel-perfect indoor and outdoor LED video walls and dynamic digital displays for advertising, events and corporate lobbies.",                                                                                                  price: "Price on Request", specs: { "Pixel Pitch": "P2 / P3 / P4 / P6 / P10", "Brightness": "Up to 6000 nits (Outdoor)", "Control": "Software / Cloud / WiFi", "IP Rating": "IP65 (Outdoor)" }, trade: { "Minimum Order Quantity": "1 sq. m.", "Delivery Time": "7–14 Working Days" } },
  // CORPORATE BRANDING
  { id: "brass-letter-signage",  title: "Brass Letter Signage",             cat: "CORPORATE BRANDING",     img: "/products/product-brass-letter.png",         desc: "Laser-cut solid brass and brass-finish 3D letters for premium corporate lobbies, hotel nameplates and luxury brand identity installations.",                                                                                      price: "Price on Request", specs: { "Material": "Solid Brass / Brass-finish SS", "Finish": "Mirror Polish / Antique / Satin", "Thickness": "2mm – 6mm", "Mounting": "Spacer / Flush / Backlit" }, trade: { "Minimum Order Quantity": "1 Set", "Delivery Time": "5–7 Working Days" } },
  { id: "mini-ss-3d-letters",    title: "Mini SS 3D Letters",               cat: "CORPORATE BRANDING",     img: "/products/product-mini-ss-3d.png",           desc: "Precision-fabricated miniature stainless steel 3D channel letters — ideal for office name-plates, counter branding and interior logo walls.",                                                                                      price: "Price on Request", specs: { "Material": "SS 304 / SS 202", "Finish": "Mirror / Hairline / Powder Coat", "Height Range": "25mm – 150mm", "Illumination": "Optional LED Backlit" }, trade: { "Minimum Order Quantity": "1 Set", "Delivery Time": "3–5 Working Days" } },
  { id: "gold-3d-brush-letters", title: "Gold 3D Brushed Letters",          cat: "CORPORATE BRANDING",     img: "/products/product-gold-3d-brush.png",        desc: "Stunning gold-brushed 3D letters and logos for corporate receptions, hospitality signage and high-end retail brand displays.",                                                                                                  price: "Price on Request", specs: { "Material": "ACP / Acrylic / SS", "Finish": "Gold Brushed / Chrome / Rose Gold", "Depth": "10mm – 50mm", "Mounting": "Studs / Adhesive / Frame" }, trade: { "Minimum Order Quantity": "1 Set", "Delivery Time": "4–6 Working Days" } },
  { id: "epoxy-fiberglass",      title: "Epoxy Fiberglass Signage",         cat: "CORPORATE BRANDING",     img: "/products/product-epoxy-fiberglass.png",     desc: "Durable epoxy-coated fiberglass signs for outdoor corporate installations — weather-resistant, UV-stable and scratch-proof for long-lasting brand presence.",                                                                      price: "Price on Request", specs: { "Material": "FRP / Fiberglass", "Coating": "Epoxy / Polyurethane", "UV Resistance": "High", "Custom Shapes": "Yes" }, trade: { "Minimum Order Quantity": "1 Unit", "Delivery Time": "5–8 Working Days" } },
  { id: "shop-signage",          title: "Premium Shop Signage",             cat: "CORPORATE BRANDING",     img: "/products/product-shop-signage.png",         desc: "End-to-end premium shop front signage solutions — from design and fabrication to installation — covering fascia boards, name-boards and entrance branding.",                                                                      price: "Price on Request", specs: { "Material": "ACP / SS / Acrylic", "Illumination": "LED / Non-lit", "Sizes": "Custom", "Installation": "Included" }, trade: { "Minimum Order Quantity": "1 Unit", "Delivery Time": "5–10 Working Days" } },
  // PRINTING & SIGNBOARDS
  { id: "eco-solvent-printing",  title: "Eco Solvent Printing",             cat: "PRINTING & SIGNBOARDS",  img: "/products/product-eco-solvent.png",          desc: "High-resolution eco-solvent printing on vinyl, banner media and canvas for retail graphics, vehicle wraps, wall murals and outdoor signage.",                                                                                      price: "Price on Request", specs: { "Resolution": "Up to 1440 DPI", "Media": "Vinyl / Canvas / Mesh / Backlit Film", "Ink Type": "Eco-Solvent (Outdoor-Grade)", "Width": "Up to 3.2 m", "Lamination": "Gloss / Matte / Anti-Scratch" }, trade: { "Minimum Order Quantity": "1 sq. ft.", "Delivery Time": "1–3 Working Days" } },
  { id: "flex-printing",         title: "Flex Banner Printing",             cat: "PRINTING & SIGNBOARDS",  img: "/products/product-flex-printing.png",        desc: "Bulk and custom flex banner printing for outdoor hoardings, event backdrops, promotional banners and retail point-of-sale displays.",                                                                                              price: "Price on Request", specs: { "Material": "13oz / 15oz / 18oz Flex", "Resolution": "720 DPI – 1440 DPI", "Finish": "Glossy / Matte", "Grommets": "Every 2 ft. (Standard)" }, trade: { "Minimum Order Quantity": "10 sq. ft.", "Delivery Time": "1–2 Working Days" } },
  { id: "outdoor-signboard",     title: "Outdoor Signboard",                cat: "PRINTING & SIGNBOARDS",  img: "/products/product-outdoor.jpg",              desc: "Weather-sealed outdoor ACP and metal signboards with UV-print graphics for petrol pumps, roadside shops, institutional signage and directional boards.",                                                                          price: "Price on Request", specs: { "Material": "ACP / MS Sheet / Aluminium", "Print": "UV / Vinyl Graphics", "Frame": "MS / SS (Powder Coated)", "Weather Resistance": "High" }, trade: { "Minimum Order Quantity": "1 Unit", "Delivery Time": "3–5 Working Days" } },
  { id: "traffic-u-sign",        title: "Traffic & Directional Signs",      cat: "PRINTING & SIGNBOARDS",  img: "/products/product-traffic-sign.png",         desc: "Retro-reflective and illuminated traffic, parking and directional signs for commercial complexes, hospitals, townships and industrial estates.",                                                                                  price: "Price on Request", specs: { "Material": "Aluminium / MS Sheet", "Reflectivity": "Type I / Type II / Type III", "Illumination": "Optional LED Backlit", "Finish": "Powder Coat / Retro-Reflective Film" }, trade: { "Minimum Order Quantity": "5 Units", "Delivery Time": "3–5 Working Days" } },
  { id: "wayfinding-signage",    title: "Wayfinding Signage System",        cat: "PRINTING & SIGNBOARDS",  img: "/products/product-wayfinding.jpg",           desc: "Comprehensive wayfinding and environmental graphics systems for malls, hospitals, airports and corporate campuses — designed for clarity and brand harmony.",                                                                      price: "Price on Request", specs: { "Material": "SS / ACP / Acrylic", "Includes": "Directory, Overhead, Floor & Wall Signs", "Illumination": "Optional LED", "Finish": "Custom Brand Colors" }, trade: { "Minimum Order Quantity": "1 System", "Delivery Time": "10–15 Working Days" } },
];

export const PRODUCTS: Product[] = RAW_PRODUCTS;
